### ISSUE TITLE
https://arxiv.org/abs/2003.02320

### ISSUE THREAD

**Issue by francisglee** [agitter/manubot-awesome-list#10]
#https://github.com/yangkky/Machine-learning-for-proteins/issues/16

**Comment by francisglee** [comment]
as I'm not a contributor, I can't label these issues.

**Comment by agitter** [comment]
This is just a repository I use for testing Manubot-related ideas, but I'll label this issue anyway to demonstrate the workflow.

**Comment by francisglee** [comment]
awesome!  I was also just testing it as well.  glad to see the pr was merged.
